Repository hakadoriya/gh-xz, pull requests merged in 2025-01, with the labels that each got.

#1 feat: Init
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/release.yml
  .github/workflows/auto-assign.yml
  .github/workflows/final-newline-checker.yml
  .github/workflows/label-checker.yml
  .github/workflows/task-list-checker.yml
  .github/workflows/typo-checker.yml
  README.md
  action.yml
  gh-pr-update-comment
Labels: feat

#3 fix: Fix action.yml
  README.md
  action.yml
Labels: fix

#4 feat: Add self-update subcommand
  gh-pr-update-comment
Labels: feat

#5 ci: Fix misc
  .github/workflows/final-newline-checker.yml
Labels: ci

#6 BREAKING CHANGE: Create gh-exz
  README.md
  action.yml
  gh-exz
Labels: BREAKING CHANGE

#7 docs: Update README.md
  README.md
  gh-exz
Labels: docs

#9 BREAKING CHANGE: Rename gh-xz
  README.md
  gh-xz
Labels: BREAKING CHANGE

#10 feat: Add subcommand "install"
  README.md
  gh-xz
Labels: feat

#11 feat: Add subcommand "self-update"
  README.md
  gh-xz
Labels: feat

#12 feat: Add "pr-get-annotated-comment" subcommand and "pr-upsert-annotated-comment" support comment body from file with @file syntax
  README.md
  gh-xz
Labels: feat

#13 BREAKING CHANGE: Rename subcommands
  README.md
  gh-xz
Labels: BREAKING CHANGE

#14 ci: Create .github/workflows/example.yml
  .github/workflows/example.yml
  README.md
Labels: ci

#17 BREAKING CHANGE: Rename subcommands
  .github/workflows/example.yml
  README.md
  gh-xz
Labels: BREAKING CHANGE

#18 docs: Update some comments
  .github/workflows/example.yml
  README.md
  gh-xz
Labels: docs

#19 docs: Create LICENSE
  LICENSE
Labels: docs

#21 fix: Update temporary file path and create directory for new comment body file
  gh-xz
Labels: fix

#22 docs: Update README.md
  README.md
Labels: docs

#23 fix: Update temporary directory path and variable names
  gh-xz
Labels: fix

#24 fix: Update variable names
  gh-xz
Labels: fix

#25 refactor: Improve temporary directory creation and cleanup process
  gh-xz
Labels: refactor
